# Generated by Django 2.0.3 on 2018-05-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20180530_1021'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profilepictures',
            table='profile_pics',
        ),
    ]
