# Generated by Django 2.0.3 on 2018-05-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_auto_20180530_1021'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='tvs_comments',
        ),
        migrations.AlterModelTable(
            name='likes',
            table='tvs_likes',
        ),
        migrations.AlterModelTable(
            name='messages',
            table='tvs_messages',
        ),
        migrations.AlterModelTable(
            name='newsfeed',
            table='tvs_newsfeed',
        ),
        migrations.AlterModelTable(
            name='notifications',
            table='tvs_notifications',
        ),
        migrations.AlterModelTable(
            name='profilepictures',
            table='tvs_profile_pics',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='tvs_user_info',
        ),
    ]
