# Generated by Django 2.0.3 on 2018-05-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0004_auto_20180530_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepictures',
            name='profile_pic',
            field=models.FileField(upload_to='profile_pics/'),
        ),
    ]
